version: "3.4"

services:
  flowise:
    build: .
    image: graphgpt
    restart: always
    ports:
      - "10000:3000"
    volumes:
      - .data:/var/flowise
    environment:
      - HOME=/var/flowise
    env_file:
      - .env