version: "3.4"

services:
  flowise:
    build:
      context: .
      args:
        REACT_APP_TELEGRAM_BOT_ID: ${REACT_APP_TELEGRAM_BOT_ID}
    image: graphgpt
    restart: always
    ports:
      - "10000:3000"
    volumes:
      - .data:/var/flowise
    environment:
      - HOME=/var/flowise
    env_file:
      - .env